name: CI/CD Pipeline Free Deployment

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-build:
    name: Test and Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run basic validation
      run: |
        echo "Validating project structure..."
        python -c "import src; print('✓ Source imports work')"
        python -c "from src.logger import logging; logging.info('✓ Logger works')"
        python -c "import app; print('✓ App imports work')"
        echo "All validations passed!"

    - name: Build Docker image
      run: |
        docker build -t vehicle-ml-app .

    - name: Test Docker container
      run: |
        docker run -d --name test-container -p 5000:5000 vehicle-ml-app
        sleep 10
        docker logs test-container
        docker stop test-container
        docker rm test-container

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: docker-image
        path: .
        retention-days: 1

  deploy-preview:
    name: Deploy to Render Preview
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
    - name: Deploy Preview
      run: |
        echo "This would trigger a preview deployment on Render"
        echo "Render automatically builds from PR branches"
        echo "Preview URL would be available here once configured"

  # Optional: Deploy to Railway (uncomment if using Railway)
  # deploy-railway:
  #   name: Deploy to Railway
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/main'
  #   
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v4
  #   
  #   - name: Deploy to Railway
  #     uses: railway-org/railway-action@v1
  #     with:
  #       railway_token: \${{ secrets.RAILWAY_TOKEN }}
  #       service: vehicle-ml-app